import sys
import os

from PyQt6.QtSql import QSqlDatabase, QSqlTableModel
from PyQt6.QtWidgets import QApplication, QMainWindow
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 580)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        Form.setFont(font)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(540, 0, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Mistral")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(parent=Form)
        self.tabWidget.setGeometry(QtCore.QRect(20, 50, 661, 511))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.TextElideMode.ElideLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableView = QtWidgets.QTableView(parent=self.tab)
        self.tableView.setGeometry(QtCore.QRect(10, 50, 631, 411))
        self.tableView.setObjectName("tableView")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 271, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 10, 261, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 10, 75, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.tableView_2 = QtWidgets.QTableView(parent=self.tab2)
        self.tableView_2.setGeometry(QtCore.QRect(10, 50, 631, 411))
        self.tableView_2.setAlternatingRowColors(False)
        self.tableView_2.setShowGrid(True)
        self.tableView_2.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.tableView_2.setObjectName("tableView_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.tab2)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 10, 271, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.tab2)
        self.lineEdit_4.setGeometry(QtCore.QRect(290, 10, 261, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton = QtWidgets.QPushButton(parent=self.tab2)
        self.pushButton.setGeometry(QtCore.QRect(560, 10, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab2, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 10, 271, 22))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(290, 10, 261, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.tableView_3 = QtWidgets.QTableView(parent=self.tab_2)
        self.tableView_3.setGeometry(QtCore.QRect(10, 50, 631, 381))
        self.tableView_3.setObjectName("tableView_3")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(560, 10, 75, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Laundry Manajemen"))
        self.label.setText(_translate("Form", ""))
        self.pushButton_2.setText(_translate("Form", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Transaksi"))
        self.pushButton.setText(_translate("Form", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("Form", "Pelanggan"))
        self.pushButton_3.setText(_translate("Form", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Paket"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Record"))


class MainWindow(QMainWindow, Ui_Form):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    Form = MainWindow()
    Form.show()
    sys.exit(app.exec())
